server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 60000
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
spring:
  thymeleaf:
    render-hidden-markers-before-checkboxes: true

---

spring:
  config:
    activate:
      on-profile: local
  security:
    user:
      name: user
      password: password
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, beans, conditions, configprops, env, loggers, metrics, mappings, sessions
nba:
  service-url: http://localhost:8080/stubs/nba-service
  api-key: blah
  club-rel: clubs
  team-rel: teams
  player-rel: players

---

spring:
  config:
    activate:
      on-profile: api-spec
  security:
    user:
      name: user
      password: password
server:
  port: 36543
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info
nba:
  service-url: http://localhost:36543/stubs/nba-service
  api-key: blahblahblah
  club-rel: clubs
  team-rel: teams
  player-rel: players

---

spring:
  config:
    activate:
      on-profile: functional-spec
  security:
    user:
      name: user
      password: password
server:
  port: 36544
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info
nba:
  service-url: http://localhost:36544/stubs/nba-service
  api-key: wibble
  club-rel: clubs
  team-rel: teams
  player-rel: players